### ISSUE TITLE
[Proposal] Change nutrition facts layout

### ISSUE THREAD

**Issue by msamoylov** [ilvar/nutria#4]
Consider rendering a nicer lists with:

```
<dl class="dl-horizontal">
  <dt>...</dt>
  <dd>...</dd>
</dl>
```

An example: https://www.dropbox.com/s/v9nfffxlphdfhhg/Screenshot%202015-01-18%2016.29.11.png?dl=0

**Comment by ilvar** [comment]
I thought of it first, but it would occupy much more space. Maybe hide panel body by default and slide it down on click on header?

**Comment by msamoylov** [comment]
Maybe a grid will be more applicable here. Four columns for desktop, two-three for tablets and a single column for mobile.

http://getbootstrap.com/css/#grid-example-mixed-complete

**Comment by ilvar** [comment]
Done in https://github.com/ilvar/nutria/commit/fe1268148e9bf2c3cd01235ba6cc233fa057e338
